let csrf='',signup=false,selected=null,parent=null;const $=s=>document.querySelector(s);
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function notice(s){$('#notice').textContent=s;}
async function api(action,data){let r;try{r=await fetch('/api?action='+action,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify({...data,csrf}):undefined,signal:AbortSignal.timeout(15000)});}catch(e){throw Error('Connection interrupted. Retrying status automatically; your task stays saved.');}const v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v;}
async function session(){const s=await api('session');csrf=s.csrf;$('#auth').hidden=!!s.user;$('#workspace').hidden=!s.user;$('#account').replaceChildren();if(s.user){$('#account').append(node('span',s.user.email));const b=node('button','Log out','secondary');b.onclick=async()=>{await api('logout',{});location.reload();};$('#account').append(b);await state();}}
$('#toggle-auth').onclick=()=>{signup=!signup;$('#invite-label').hidden=!signup;$('#auth-submit').textContent=signup?'Create account':'Log in';$('#toggle-auth').textContent=signup?'Use existing account':'Create an account';};
$('#auth-form').onsubmit=async e=>{e.preventDefault();try{await api(signup?'signup':'login',Object.fromEntries(new FormData(e.target)));notice('');await session();}catch(x){notice(x.message);}};
$('#task-form').onsubmit=async e=>{e.preventDefault();try{const t=await api('task',{prompt:$('#prompt').value,parent});$('#prompt').value='';parent=null;notice('Task queued: '+t.id.slice(0,8));await state();}catch(x){notice(x.message);}};
$('#wa-connect').onclick=async()=>{try{await api('whatsapp',{connect:true});await state();}catch(x){notice(x.message);}};
$('#wa-disconnect').onclick=async()=>{try{await api('whatsapp',{connect:false});await state();}catch(x){notice(x.message);}};
$('#close-activity').onclick=()=>{selected=null;$('#activity').hidden=true;};
async function evidence(id){selected=id;$('#activity').hidden=false;const r=await api('events&id='+encodeURIComponent(id));$('#events').replaceChildren();for(const e of r.events){const item=node('details',undefined,'event');item.append(node('summary',e.role+' · '+e.kind+' · '+new Date(e.created*1000).toLocaleTimeString()),node('pre',e.detail));$('#events').append(item);}}
async function state(){try{const s=await api('state'); if($('#notice').textContent.startsWith('Connection interrupted.'))notice('');renderRoles(s.roles||[]);$('#stat-active').textContent=s.tasks.filter(t=>['queued','working'].includes(t.status)).length;$('#stat-ready').textContent=s.tasks.filter(t=>t.status==='ready').length;$('#stat-chat').textContent=s.tasks.filter(t=>t.status==='answered').length;$('#tasks').replaceChildren();if(!s.tasks.length)$('#tasks').append(node('p','Your first project starts here.','muted'));for(const t of s.tasks){const card=node('article',undefined,'task'+(t.status==='answered'?' task-chat':''));card.append(node('span',t.status.replaceAll('_',' '),'badge'),node('h3',t.prompt.slice(0,140)),node('p',(t.role||(t.status==='answered'?'Assistant':t.status==='ready'?'Delivered':'Queue'))+' · Revision '+t.cycle+' · '+t.model_calls+' model calls','muted'));renderGoal(card,t);if(t.error)card.append(node('p',t.error,'error'));if(t.summary)card.append(node('pre',t.summary,'task-answer'));let team=[];try{team=JSON.parse(t.team||'[]');}catch{}if(team.length)card.append(node('p',(t.mode||'task')+' · Assigned team: '+team.join(', '),'muted'));const b=node('button','View evidence','secondary');b.onclick=()=>evidence(t.id).catch(x=>notice(x.message));card.append(b);if(!['queued','working'].includes(t.status)){const revise=node('button',t.status==='answered'?'Continue conversation':'Revise project','secondary');revise.onclick=()=>{if(t.status==='answered'){parent=null;$('#prompt').value='';$('#prompt').focus();notice('Send your next message. Your recent conversation is available to the assistant.');return;}parent=t.id;$('#prompt').value='Revise this existing project: ';$('#prompt').focus();notice('Revising project '+t.id.slice(0,8)+'. Describe the changes and start building.');};card.append(revise);}if(t.status==='ready'){for(const output of t.deliverables||[]){const link=node('a','Download '+output.path.split('/').pop(),'download primary-download');link.href='/download?id='+t.id+'&file='+encodeURIComponent(output.path);card.append(link);}const a=node('a','Download source ZIP','download');a.href='/download?id='+t.id;card.append(a);}if(['queued','working'].includes(t.status)){const c=node('button','Cancel','secondary');c.onclick=async()=>{await api('cancel',{id:t.id});await state();};card.append(c);}$('#tasks').append(card);}$('#wa-status').textContent=s.whatsapp.status.replaceAll('_',' ');$('#wa-qr').hidden=!s.whatsapp.qr;if(s.whatsapp.qr)$('#wa-qr').src=s.whatsapp.qr;if(selected)await evidence(selected);}catch(x){if(x.message!=='Log in first')notice(x.message);}}
session().catch(x=>notice(x.message));setInterval(()=>{if(!$('#workspace').hidden)state();},5000);

function renderRoles(roles){ const box=document.querySelector('#roles-current');box.replaceChildren();for(const r of roles){box.append(node('span',r.role+' · '+r.status+' · '+Math.max(0,Math.round(Date.now()/1000-r.updated))+'s','role-chip'));}}

document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{parent=null;document.querySelector('#prompt').value=b.dataset.example;document.querySelector('#prompt').focus();});

function renderGoal(card,task){
 let p;try{p=JSON.parse(task.progress||'{}');}catch{return;}if(!p.goal)return;
 const box=node('details',undefined,'goal-contract');box.append(node('summary','Goal & acceptance · '+(p.goal_achieved?'independently approved':(p.stage||'understanding'))));
 box.append(node('p',p.goal,'goal-title'));
 if(p.deliverables?.length)box.append(node('p','Expected result: '+p.deliverables.map(x=>x.path).join(', '),'muted'));
 const checks=new Map((p.verification||[]).map(x=>[x.id,x]));const list=node('ul');
 for(const criterion of p.criteria||[]){const result=checks.get(criterion.id);const item=node('li');item.append(node('strong',(result?(result.passed?'Passed':'Needs repair'):'Pending')+' · '+criterion.id+' '),node('span',criterion.requirement));if(result)item.append(node('p',result.reason+' · Evidence '+result.evidence_ids.join(', '),'muted'));list.append(item);}box.append(list);
 for(const issue of p.review_issues||[])box.append(node('p','Reviewer: '+issue,'error'));card.append(box);
}
